name: ADMC CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build software using docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      - run:  sudo apt-get update
      - run:  sudo apt-get install -y build-essential devscripts debhelper gcc g++ catch cmake cmake-data cmake-qt-gui qttools5-dev-tools qtbase5-dev qtbase5-dev-tools qtbase5-private-dev samba-dev libldap-dev libsasl2-dev libsmbclient-dev libcmocka-dev doxygen libg2-dev libpcre3-dev libkrb5-dev libcmocka-dev qttools5-dev
      - name: Create build folder
        run:  mkdir build
      - name: Build ADMC
        run:  cd build && cmake .. -DADMC_BUILD_DEB=1 && make -j 12     
